### ISSUE TITLE
[ENHANCEMENT] Implement Comprehensive Pre-commit Hooks and Code Quality Checks

### ISSUE THREAD

**Issue by davidamacey** [davidamacey/OpenTranscribe#24]
## Problem Statement
We need to establish a robust pre-commit hook system to ensure code quality, security, and consistency across the codebase. Currently, the project lacks automated code quality checks, which can lead to inconsistent code style, potential security issues, and technical debt.

## Solution
Implement a comprehensive pre-commit hook system using `pre-commit` framework that runs various linters, formatters, and security checks before each commit.

### Core Tools
1. **pre-commit** - Framework for managing and maintaining multi-language pre-commit hooks
2. **Ruff** - Extremely fast Python linter and code formatter (replaces flake8, isort, and more)
3. **Black** - Uncompromising Python code formatter
4. **mypy** - Static type checker for Python
5. **prettier** - Code formatter for frontend files (JavaScript/TypeScript, JSON, YAML, Markdown, etc.)
6. **eslint** - JavaScript/TypeScript linter
7. **gitleaks** - Detect hardcoded secrets and credentials
8. **bandit** - Security linter for Python
9. **safety** - Check Python dependencies for known security vulnerabilities
10. **trivy** - Comprehensive security scanner for containers and dependencies

#### `.pre-commit-config.yaml`
```yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json
    -   id: check-added-large-files
        args: [--maxkb=10240]  # 10MB max file size
    -   id: check-merge-conflict
    -   id: check-toml
    -   id: check-vcs-permalinks
    -   id: mixed-line-ending
        args: [--fix=lf]

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.2
    hooks:
    -   id: ruff
        args: [--fix, --show-fixes]
    -   id: ruff-format
        args: [--fix]

-   repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
    -   id: black
        language_version: python3.11

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
    -   id: mypy
        additional_dependencies: [types-requests, types-python-dateutil, types-pyyaml]
        args: [--strict, --ignore-missing-imports]

-   repo: https://github.com/prettier/prettier
    rev: '3.2.4'
    hooks:
    -   id: prettier
        types_or: [javascript, typescript, json, yaml, html, css, scss, markdown, graphql]
        args: [--write, --prose-wrap=always]

-   repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.1
    hooks:
    -   id: gitleaks
        args: ["--verbose", "--redact"]

-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.7
    hooks:
    -   id: bandit
        args: ["-c", "pyproject.toml"]

-   repo: https://github.com/pyupio/safety
    rev: 2.3.5
    hooks:
    -   id: safety
        args: ["check", "--full-report"]
        pass_filenames: false
```

#### `pyproject.toml` (for Python tooling)
```toml
[tool.black]
line-length = 100
target-version = ['py311']
include = '\.pyi?$'

[tool.ruff]
line-length = 100
target-version = "py311"
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # pyflakes
    "I",   # isort
    "B",   # flake8-bugbear
    "C4",  # flake8-comprehensions
    "E7",  # flake8-assertive
    "FBT", # flake8-boolean-trap
    "ICN", # flake8-import-conventions
    "ISC", # flake8-implicit-str-concat
    "N",   # pep8-naming
    "PTH", # flake8-use-pathlib
    "RUF", # Ruff-specific rules
    "SIM", # flake8-simplify
    "T20", # flake8-print
    "UP",  # pyupgrade
    "YTT", # flake8-2020
]
ignore = [
    "E501",  # Line too long - Handled by black
    "W503",  # Line break before binary operator - Handled by black
]

[tool.ruff.isort]
known-first-party = ["app"]

[bandit]
exclude_dirs = ["tests", "venv", ".venv", "node_modules"]
targets = ["app"]
skips = ["B101"]  # Skip assert_used check in tests

[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_unreachable = true
strict_equality = true

[[tool.mypy.overrides]]
module = [
    "alembic.*",
    "pydantic.*",
    "sqlalchemy.*",
    "fastapi.*",
    "uvicorn.*",
]
disallow_untyped_defs = false
```

### 2. Installation and Setup

1. Install pre-commit:
   ```bash
   pip install pre-commit
   ```

2. Install the git hook scripts:
   ```bash
   pre-commit install
   ```

3. Run against all files:
   ```bash
   pre-commit run --all-files
   ```

### 3. CI Integration

Add to GitHub Actions workflow (`.github/workflows/pre-commit.yml`):

```yaml
name: pre-commit

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  schedule:
    - cron: '0 0 * * 0'  # Weekly

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
      - name: Run pre-commit
        run: pre-commit run --all-files
```

## Acceptance Criteria

- [ ] Pre-commit hooks are installed and working locally
- [ ] All existing code passes the pre-commit checks
- [ ] CI pipeline includes pre-commit checks
- [ ] Documentation is updated with setup instructions
- [ ] Team is briefed on the new workflow

## Documentation

Add to `CONTRIBUTING.md`:

```markdown
## Development Setup

### Pre-commit Hooks

This project uses pre-commit hooks to ensure code quality and consistency. To set up:

1. Install pre-commit:
   ```bash
   pip install pre-commit
   ```

2. Install the git hook scripts:
   ```bash
   pre-commit install
   ```

3. Run against all files:
   ```bash
   pre-commit run --all-files
   ```

The hooks will now run automatically on `git commit`. To run manually:

```bash
pre-commit run  # Run on staged files
pre-commit run --all-files  # Run on all files
```
```

## Future Enhancements

1. Add commit message linter (commitlint)
2. Add dependency updates checking (dependabot)
3. Add code coverage enforcement
4. Add spell checking
5. Add markdown link checking
