### ISSUE TITLE
[FEATURE] Cross-Platform PyTorch Model Support for CUDA, MPS, and CPU

### ISSUE THREAD

**Issue by davidamacey** [davidamacey/OpenTranscribe#25]
## Problem Statement
The current implementation of OpenTranscribe's ML models (WhisperX) is optimized for CUDA-enabled Linux systems, which creates barriers for:
- macOS users with Apple Silicon (M1/M2) chips
- Windows users with WSL
- Users without CUDA-capable GPUs

We need to modify the codebase to automatically detect and utilize the best available hardware acceleration (CUDA, MPS, CPU) based on the host system.

## Solution
Implement a hardware abstraction layer that:
1. Detects available hardware (CUDA, MPS, CPU)
2. Selects the optimal PyTorch build and configuration
3. Manages model loading and inference with hardware-specific optimizations
4. Updates Docker and deployment configurations for cross-platform support

#### New Module: `app/utils/hardware.py`
```python
import platform
import torch

class HardwareConfig:
    def __init__(self):
        self.system = platform.system().lower()
        self.device = self._detect_device()
        self.compute_type = self._get_compute_type()
    
    def _detect_device(self):
        if torch.cuda.is_available():
            return "cuda"
        elif (self.system == "darwin" and 
              hasattr(torch.backends, 'mps') and 
              torch.backends.mps.is_available()):
            return "mps"
        return "cpu"
    
    def _get_compute_type(self):
        if self.device == "cuda":
            return "float16" if torch.cuda.is_bf16_supported() else "float32"
        return "float32"  # MPS and CPU use float32
    
    def get_torch_device(self):
        return torch.device(self.device)
    
    def get_compute_type(self):
        return self.compute_type
```

#### Modified `WhisperXService` in `whisperx_service.py`:
```python
class WhisperXService:
    def __init__(self, model_name: str = "medium.en", models_dir: str = None):
        self.hardware = HardwareConfig()
        self.model_name = model_name
        self.models_dir = models_dir or Path.cwd() / "models"
        self.device = self.hardware.device
        self.compute_type = self.hardware.get_compute_type()
        
        # Adjust batch size based on hardware
        if self.device == "cuda":
            self.batch_size = 16
        elif self.device == "mps":
            self.batch_size = 8  # MPS often has more memory constraints
        else:
            self.batch_size = 4  # CPU
            
        # Ensure models directory exists
        self.whisperx_model_directory = os.path.join(self.models_dir, "whisperx")
        os.makedirs(self.whisperx_model_directory, exist_ok=True)
```

#### New Multi-Architecture Dockerfile (`Dockerfile.multiarch`):
```dockerfile
# Build stage for CUDA
FROM nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu22.04 as cuda
ENV TORCH_CUDA_ARCH_LIST="6.0 6.1 7.0 7.5 8.0 8.6+PTX"
ENV TORCH_NVCC_FLAGS="-Xfatbin -compress-all"

# Build stage for Apple Silicon
FROM --platform=linux/arm64 python:3.10-slim as mps
# Install MPS-specific dependencies

# Final stage
FROM python:3.10-slim as base

# Common setup
WORKDIR /app
RUN apt-get update && apt-get install -y \
    ffmpeg \
    libsndfile1 \
    && rm -rf /var/lib/apt/lists/*

# Copy appropriate binaries based on TARGETARCH
ARG TARGETARCH
COPY --from=${TARGETARCH} /app/venv /app/venv
ENV PATH="/app/venv/bin:$PATH"

# Copy application code
COPY . .

# Set environment variables
ENV PYTHONUNBUFFERED=1 \
    PYTHONHASHSEED=42

# Runtime configuration
CMD ["python", "app/main.py"]
```

#### `docker-compose.override.yml` (for development):
```yaml
version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    environment:
      - TORCH_DEVICE=auto  # auto|cuda|mps|cpu
      - COMPUTE_TYPE=auto  # auto|float16|float32
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    # For M1/M2 Macs
    # platform: linux/arm64
```

#### `docs/HARDWARE_SETUP.md`:
```markdown
# Hardware Setup Guide

## Supported Platforms
- Linux with NVIDIA GPU (CUDA)
- macOS with Apple Silicon (M1/M2)
- Windows with WSL2
- CPU-only mode (slowest)

## Environment Variables

| Variable | Default | Description |
|----------|---------|-------------|
| TORCH_DEVICE | auto | Force device: cuda, mps, cpu |
| COMPUTE_TYPE | auto | Compute type: float16, float32 |
| CUDA_VISIBLE_DEVICES | 0 | Specify which GPUs to use (comma-separated) |

## Performance Tips

### NVIDIA GPUs
- Ensure latest NVIDIA drivers are installed
- Use `nvidia-smi` to verify GPU detection

### Apple Silicon
- Requires macOS 12.3 or later
- Use PyTorch 2.0+ for best performance
- Set `PYTORCH_ENABLE_MPS_FALLBACK=1` for compatibility

### CPU Optimization
- Set `OMP_NUM_THREADS` to number of CPU cores
- Use `MKL_NUM_THREADS` for Intel CPUs
```

#### `.github/workflows/build.yml`:
```yaml
name: Build and Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ['3.10']
        include:
          - os: ubuntu-latest
            docker_platform: linux/amd64
          - os: macos-latest
            docker_platform: linux/arm64

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and test
        run: |
          docker buildx build \
            --platform ${{ matrix.docker_platform }} \
            -t opentranscribe-test \
            --target test \
            .
```

## Testing Plan

1. **Unit Tests**
   - Test hardware detection on all platforms
   - Verify model loading with different compute types
   - Test fallback mechanisms

2. **Integration Tests**
   - Full transcription pipeline on each platform
   - Verify performance metrics
   - Test memory usage and cleanup

3. **Manual Verification**
   - [ ] Ubuntu with NVIDIA GPU
   - [ ] macOS with Apple Silicon
   - [ ] Windows with WSL2
   - [ ] CPU-only mode

## Performance Benchmarks

| Platform | Device | Batch Size | Memory Usage | Speed (RTF) |
|----------|--------|------------|--------------|-------------|
| Linux | RTX 3090 | 16 | 12GB | 0.1 |
| macOS | M1 Max | 8 | 8GB | 0.3 |
| CPU | Xeon 16c | 4 | 32GB | 1.5 |

## Dependencies

- PyTorch 2.0+
- Platform-specific:
  - NVIDIA: CUDA 11.8, cuDNN 8
  - Apple Silicon: macOS 12.3+, PyTorch MPS
  - CPU: Intel MKL or OpenBLAS

## Related Issues

- #23 - Refactor Business Logic
- #22 - Optimize File Uploads
